puts "The students of the Villains Academy"
puts "_____________"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Coleone"
puts "Alex Delarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffery Baratheon"
puts "Norman Bates"
print "Overall, we have "
print 11
puts " great students"
